version: "3.6"
networks:
  services:
    external: true
configs:
  traefik:
    external:
      name: traefik1
services:
  traefik:
    image: traefik:1.7.1
    command:
      - "--api"
      - "--docker"
      - "--defaultentrypoints=http,https"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--retry"
      - "--acme"
      - "--acme.email=dev@bartvh.nl"
      - "--acme.storage=/acme.json"
      - "--acme.entryPoint=https"
      - "--acme.tlsChallenge"
      - "--acme.onHostRule=true"
    ports:
      - "80:80"
      - "443:443"
      - "18080:8080" # --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/acme.json:/acme.json
    networks:
      - services
